//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controle.Acoes.Portal.Auxiliares.Mensagens {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidacaoMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidacaoMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Controle.Acoes.Portal.Auxiliares.Mensagens.ValidacaoMsg", typeof(ValidacaoMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não contém uma data válida.
        /// </summary>
        internal static string DataInvalida {
            get {
                return ResourceManager.GetString("DataInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} e {1} devem ser iguais.
        /// </summary>
        internal static string DevemSerIguais {
            get {
                return ResourceManager.GetString("DevemSerIguais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é requerido(a).
        /// </summary>
        internal static string EhRequerido {
            get {
                return ResourceManager.GetString("EhRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não contém um guid válido.
        /// </summary>
        internal static string GuidInvalido {
            get {
                return ResourceManager.GetString("GuidInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve conter no máximo {1} caractéres.
        /// </summary>
        internal static string MaximoDeCaracteres {
            get {
                return ResourceManager.GetString("MaximoDeCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve conter no mínimo {1} caractéres.
        /// </summary>
        internal static string MinimoDeCaracteres {
            get {
                return ResourceManager.GetString("MinimoDeCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não é válido(a).
        /// </summary>
        internal static string NaoEhValido {
            get {
                return ResourceManager.GetString("NaoEhValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não pode ser vazio(a).
        /// </summary>
        internal static string NaoPodeSerVazio {
            get {
                return ResourceManager.GetString("NaoPodeSerVazio", resourceCulture);
            }
        }
    }
}
